services:
  db:
    image: postgres:15
    container_name: tradebot_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tradebot
      POSTGRES_USER: tradebot
      POSTGRES_PASSWORD: tradebot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tradebot_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  db_data:
